using System.Diagnostics;
using Npgsql;

namespace Estoque.Helpers
{
    public static class SupabaseSchemaInitializer
    {
        public static void EnsureCreated()
        {
            try
            {
                using (var connection = new NpgsqlConnection(SupabaseConnectionSettings.GetConnectionString()))
                {
                    connection.Open();

                    using (var command = connection.CreateCommand())
                    {
                        command.CommandText = @"
CREATE TABLE IF NOT EXISTS public.""Produtoes""
(
    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ""Nome"" character varying(100) NOT NULL,
    ""Descricao"" character varying(300),
    ""Preco"" numeric(18,2) NOT NULL,
    ""ImagemUrl"" character varying(500),
    ""Quantidade"" integer NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS public.""Movimentacaos""
(
    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ""ProdutoId"" integer NOT NULL,
    ""NomeProduto"" text,
    ""Tipo"" text,
    ""Quantidade"" integer NOT NULL,
    ""Data"" timestamp without time zone NOT NULL
);

CREATE TABLE IF NOT EXISTS public.""Usuarios""
(
    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ""Nome"" character varying(100) NOT NULL,
    ""Email"" character varying(150) NOT NULL,
    ""SenhaHash"" character varying(64) NOT NULL,
    ""PodeAcessarAdmin"" boolean NOT NULL DEFAULT false,
    ""DataCadastro"" timestamp without time zone NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS ""IX_Usuarios_Email"" ON public.""Usuarios"" (""Email"");";

                        command.ExecuteNonQuery();
                    }
                }
            }
            catch (NpgsqlException ex)
            {
                Trace.TraceError("Supabase schema initialization failed: " + ex);
            }
            catch (System.Exception ex)
            {
                Trace.TraceError("Supabase schema initialization failed: " + ex);
            }
        }
    }
}
